/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 3.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddAccountSchema {
    /// Your desired username.
    #[serde(rename = "username")]
    pub username: String,
    /// Your password.
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
}

impl AddAccountSchema {
    pub fn new(username: String, password: String) -> AddAccountSchema {
        AddAccountSchema {
            username,
            password,
            email: None,
        }
    }
}

