/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 4.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BankSchema {
    /// Maximum slots in your bank.
    #[serde(rename = "slots")]
    pub slots: i32,
    /// Bank expansions.
    #[serde(rename = "expansions")]
    pub expansions: i32,
    /// Next expansion cost.
    #[serde(rename = "next_expansion_cost")]
    pub next_expansion_cost: i32,
    /// Quantity of gold in your bank.
    #[serde(rename = "gold")]
    pub gold: i32,
}

impl BankSchema {
    pub fn new(slots: i32, expansions: i32, next_expansion_cost: i32, gold: i32) -> BankSchema {
        BankSchema {
            slots,
            expansions,
            next_expansion_cost,
            gold,
        }
    }
}

