/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 3.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeOrderSchema {
    /// Order id.
    #[serde(rename = "id")]
    pub id: String,
    /// Seller account name.
    #[serde(rename = "seller")]
    pub seller: String,
    /// Item code.
    #[serde(rename = "code")]
    pub code: String,
    /// Item quantity.
    #[serde(rename = "quantity")]
    pub quantity: i32,
    /// Item price per unit.
    #[serde(rename = "price")]
    pub price: i32,
    /// Order created at.
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl GeOrderSchema {
    pub fn new(id: String, seller: String, code: String, quantity: i32, price: i32, created_at: String) -> GeOrderSchema {
        GeOrderSchema {
            id,
            seller,
            code,
            quantity,
            price,
            created_at,
        }
    }
}

