/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 3.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TasksRewardDataSchema {
    /// Cooldown details.
    #[serde(rename = "cooldown")]
    pub cooldown: Box<models::CooldownSchema>,
    /// Reward details.
    #[serde(rename = "rewards")]
    pub rewards: Box<models::TaskRewardsSchema>,
    /// Player details.
    #[serde(rename = "character")]
    pub character: Box<models::CharacterSchema>,
}

impl TasksRewardDataSchema {
    pub fn new(cooldown: models::CooldownSchema, rewards: models::TaskRewardsSchema, character: models::CharacterSchema) -> TasksRewardDataSchema {
        TasksRewardDataSchema {
            cooldown: Box::new(cooldown),
            rewards: Box::new(rewards),
            character: Box::new(character),
        }
    }
}

