/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskSchema {
    /// Task objective.
    #[serde(rename = "code")]
    pub code: String,
    /// The type of task.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The total required to complete the task.
    #[serde(rename = "total")]
    pub total: i32,
}

impl TaskSchema {
    pub fn new(code: String, r#type: Type, total: i32) -> TaskSchema {
        TaskSchema {
            code,
            r#type,
            total,
        }
    }
}
/// The type of task.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "monsters")]
    Monsters,
    #[serde(rename = "items")]
    Items,
}

impl Default for Type {
    fn default() -> Type {
        Self::Monsters
    }
}

