/*
 * Artifacts API
 *
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TasksRewardFullSchema {
    /// Item code.
    #[serde(rename = "code")]
    pub code: String,
    /// Minimum quantity of item.
    #[serde(rename = "min_quantity")]
    pub min_quantity: i32,
    /// Maximum quantity of item.
    #[serde(rename = "max_quantity")]
    pub max_quantity: i32,
    /// Item odds.
    #[serde(rename = "odds")]
    pub odds: f64,
}

impl TasksRewardFullSchema {
    pub fn new(code: String, min_quantity: i32, max_quantity: i32, odds: f64) -> TasksRewardFullSchema {
        TasksRewardFullSchema {
            code,
            min_quantity,
            max_quantity,
            odds,
        }
    }
}

